### ISSUE TITLE
turbonomic operator deploy in ocp failed

### ISSUE THREAD

**Issue by rainshuzi** [turbonomic/t8c-install#10]
I deployed the turbonomic operator in OCP4.6 and  installed the XI CR sequentially . But, some pods are ready and some are not ready. 
<img width="861" alt="截屏2021-07-28 下午4 13 36" src="https://user-images.githubusercontent.com/20263045/127294947-e3753c5e-7c80-4e8c-b4eb-a2e3ab86a339.png">
<img width="590" alt="截屏2021-07-28 下午5 05 28" src="https://user-images.githubusercontent.com/20263045/127295912-bbdde2f8-eb74-45c7-b5d7-22bae2f6fb27.png">

The describe information of non-ready pods :
<img width="1280" alt="截屏2021-07-28 下午5 11 10" src="https://user-images.githubusercontent.com/20263045/127296748-59abd4c1-bd40-40b2-9d6c-7101e9ffa0a1.png">

The rsyslog logs of db pod has errors:
<img width="1163" alt="截屏2021-07-28 下午3 41 22" src="https://user-images.githubusercontent.com/20263045/127295029-12c0673e-96cf-43a4-9ac4-3d6ee9d67d10.png">

as i have reinstalled turbonomic with 8.2.3 and 8.1.6 version, the same result.

[rsyslog.log](https://github.com/turbonomic/t8c-install/files/6891909/rsyslog.log)

how can i do to fix this issue?

**Comment by esara** [comment]
it appears that the database is not running, which is a dependency for other components, so they wont report ready, until the database is ready.
did you follow the openshift requirements at https://github.com/turbonomic/t8c-install/blob/master/DEPLOY.md
specifically, you can either specify the fsGroup based on the assigned uid range for a project with a restricted scc, or you can just change to an anyuid scc for the project (see the link above for better documentation)

**Comment by rainshuzi** [comment]
thanks esara, 
i followed the guide and set the scc, but database is failed with error as before.
may be  the database startup error caused the issue, any other ideas?

**Comment by esara** [comment]
@rainshuzi the "cannot open table" error message seems to indicate a storage problem, are you running on nfs or block storage in fyre? both should work, but typically block storage performs better, you can specify a non-default storageclass (you would have to delete and recreate the Xls custom resource to reprovision), see under https://github.com/turbonomic/t8c-install/wiki/Storage-Class-Requirements

**Comment by rainshuzi** [comment]
@esara it is worked after i changed storageclass from default(ocs-storagecluster-cephfs) to non-default(ocs-storagecluster-ceph-rbd).

thanks again.

**Comment by aishvaryaps** [comment]
@rainshuzi Where did u get the trial license from ?
