### ISSUE TITLE
Turbonomic Trial License for Kubernetes set up

### ISSUE THREAD

**Issue by aishvaryaps** [turbonomic/t8c-install#11]
I deployed turbonomic on Kubernetes. I am able to see UI as well.  Thanks to this repo. 
It is asking for license.
May I know where will I get a trial license ?
I installed a .zip file from hyper-V set up. I got a .xml file there , but that doesn't seem to work for Kubernetes set-up.
Please guide where can I install trial license file for kubernetes set up ?

**Comment by esara** [comment]
please contact the turbonomic account team at https://learn.turbonomic.com/contact-us
