### ISSUE TITLE
CRD unable to deploy in k8s 1.22.x

### ISSUE THREAD

**Issue by evat-pm** [turbonomic/t8c-install#14]
The CRD located here: https://raw.githubusercontent.com/turbonomic/t8c-install/master/operator/deploy/crds/charts_v1alpha1_xl_crd.yaml will not create a CRD in k8s 1.22.1.  This CRD represents the  latest available.  

Issue is api version: uses `apiVersion: apiextensions.k8s.io/v1beta1` and this is officially deprecated in k8s 1.22
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122 

kubectl apply shows this validation error:
`error: error validating "CRD_k8s122.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false`

Running with --validate=false won't work:
kubectl -n turbonomic apply -f CRD_k8s122.yaml --validate=false
`The CustomResourceDefinition "xls.charts.helm.k8s.io" is invalid: 
* spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
* spec.versions[1].schema.openAPIV3Schema: Required value: schemas are required`

**Comment by evat-pm** [comment]
Need to update the CRD to support the apiextentions v1 and related changes to schema.  Internally opened JIRA OM-75203

**Comment by esara** [comment]
The turbonomic platform operator configuration was migrated to the operator sdk 1.0 which generates the v1 crd instead of the beta crd which shows up publicly under
https://github.com/turbonomic/t8c-install/tree/master/operator/config
specifically the crd shows up
https://github.com/turbonomic/t8c-install/blob/master/operator/config/crd/bases/charts.helm.k8s.io_xls.yaml
