### ISSUE TITLE
t8c.sh does not respect turbo.conf's device for cluster storage

### ISSUE THREAD

**Issue by jpolenswbc** [turbonomic/t8c-install#2]
The latest AWS Marketplace version of Turbonomic is 6.4, but the current released version is 7.22. I wanted to use the latest since we have already BYOL and would like all the new features and UI. I ended up importing the OVA to create an AWS AMI from it, which worked perfectly. It started up quickly and I was able to gain SSH access. From there, it took a couple of times to figure out the gotchas of my approach compared to the documentation. Unfortunately, there was one I could not get around "easily". 

I made my modifications to the /opt/local/etc/turbo.conf file and set the device variable to "/dev/nvme1n1", which is the 250G secondary drive from the OVA. I had a couple of failed attempts executing the installer. During one of those failures, I scrolled back through the logs and noticed this:

`wipefs: error: /dev/sdb: probing initialization failed: Device or resource busy`

Here is the offending line:

https://github.com/turbonomic/t8c-install/blob/ec092ad1d6c66d26fa73a7d12872f6a3547eb900/bin/t8c.sh#L223

**Should it be corrected to the following?**    `sudo /usr/sbin/wipefs -a ${device}`

_Note: The EBS drives are /dev/nvme* and not /dev/sd* in newer instance types. A simple "trick" to get around this issue was to create a symlink to the correct drive:_   `sudo ln -s /dev/nvme1n1 /dev/sdb`

**Comment by esara** [comment]
@jpolenswbc we do not support importing an OVA as an AMI, Turbo 8 (as well as previously Turbo 7) can be deployed into an EKS cluster using https://github.com/turbonomic/t8c-install/wiki/4.-Turbonomic-Multinode-Deployment-Steps
