### ISSUE TITLE
Helm Chart gives the following error : no matches for kind "Xl" in version "charts.helm.k8s.io/v1" (Jun 14,  2022) 

### ISSUE THREAD

**Issue by devstackhub** [turbonomic/t8c-install#23]
kubectl apply -f https://raw.githubusercontent.com/turbonomic/t8c-install/master/operator/deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic

Error : 
error: unable to recognize "https://raw.githubusercontent.com/turbonomic/t8c-install/master/operator/deploy/crds/charts_v1alpha1_xl_cr.yaml": no matches for kind "Xl" in version "charts.helm.k8s.io/v1"
<img width="1675" alt="Screenshot 2022-06-14 at 09 21 23" src="https://user-images.githubusercontent.com/61521479/173517799-c15a8c02-2424-430a-8dfe-ed595b4ff69c.png">

**Comment by esara** [comment]
@devstackhub please follow the deployment steps at
https://github.com/turbonomic/t8c-install/blob/master/DEPLOY.md#installing-the-turbonomic-platform-operator-without-operator-lifecycle-manager-olm
you need to apply the custom resource definition, before you can apply the custom resource for any operator in k8s (including the t8c-operator)

**Comment by devstackhub** [comment]
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/61521479/173568223-59073c2f-bd77-430f-88b1-867cb1cbf4be.png">
Please let me know if I am doing something wrong .. I was following the
**Installing the Turbonomic Platform Operator without Operator Lifecycle Manager (OLM)** steps

**Comment by devstackhub** [comment]
Thanks it works fine @esara
