### ISSUE TITLE
Deploy instance on labeled nodes

### ISSUE THREAD

**Issue by bromaniac** [turbonomic/t8c-install#26]
Hi,

I have installed the Turbonomic Operator on Openshift and I'm trying to create an instance. We only have persistent storage on some nodes designated with a label. How can I change the nodeSelector in the CR to only deploy on nodes with a certain label?

**Comment by evat-pm** [comment]
Hi @bromaniac yes you can define nodeSelector and other types of selector strategies to control where the Turbo pods are deployed.  Note these are global, and apply to all pods.
Examples:
1. nodeSelector https://github.com/turbonomic/t8c-install/blob/02cd7d38240934aa15e3df99328c70627548d29f/operator/deploy/crds/charts_v1alpha1_xl_crd.yaml#L114 
`spec:
    global:
      nodeSelector: kubernetes.io/os=linux`
2. tolerations (which supports an array - list of tolerations) https://github.com/turbonomic/t8c-install/blob/02cd7d38240934aa15e3df99328c70627548d29f/operator/deploy/crds/charts_v1alpha1_xl_crd.yaml#L117
3. we also support affinity: https://github.com/turbonomic/t8c-install/blob/02cd7d38240934aa15e3df99328c70627548d29f/operator/deploy/crds/charts_v1alpha1_xl_crd.yaml#L122
4. you can provide a storageAnnotation on the PVC that is created https://github.com/turbonomic/t8c-install/blob/02cd7d38240934aa15e3df99328c70627548d29f/operator/deploy/crds/charts_v1alpha1_xl_crd.yaml#L155 

Hope this helps!
eva
ibm turbo product manager

**Comment by bromaniac** [comment]
Thank you @evat-pm that worked perfectly! Closing this ticket. Thank you for the quick help.
