### ISSUE TITLE
missing property in action-orchestrator in charts_v1alpha1_xl_crd.yaml 

### ISSUE THREAD

**Issue by shawsers** [turbonomic/t8c-install#4]
I have recently use the following property for the action-orchestrator but I do not see it defined in the charts_v1alpha1_xl_crd.yaml file.  See example below.  I also know there are many other properties available that are missing from the crd file as well.  If those available could be added that would be great to reference for future use.

properties:    
  action-orchestrator:        
    actionExecution.concurrentAutomatedActions: 10

thanks,

**Comment by esara** [comment]
hi Shawn, thanks - this particular property will be obsoleted soon, but your point is valid, we should document other relevant/customer facing options - I will keep this issue open for the next update.

**Comment by shawsers** [comment]
Thanks Endre!  For that particular property is it going to be replaced with something else?  Just wondering how that will work for customers that are using it currently?

**Comment by esara** [comment]
we have not decided yet, but that is not platform design question, not yet an operator custom resource option
