### ISSUE TITLE
CRD validation portion missing timescaledb and nginx parameters

### ISSUE THREAD

**Issue by evat-pm** [turbonomic/t8c-install#5]
Turbonomic supports an embedded reporting feature with timescaledb, and the Custom Resource can be configured to use an external db. The CRD is missing definitions of:
```
externalTimescaleDBName:
externalTimescaleDBIP:
```

We also allow customer to modify ngnix properties.  In 8.1 we introduced the externalTrafficPolicy parameter:
```
nginx:
    externalTrafficPolicy: Cluster
```

**Comment by evat-pm** [comment]
@esara now that remote timescaledb is supported in 8.1.5, this crd should be updated

**Comment by esara** [comment]
resolved by https://github.com/turbonomic/t8c-install/commit/df28fe55c87e012128d63279d3d47fa0eea349c4
