### ISSUE TITLE
CRD deprecated API version

### ISSUE THREAD

**Issue by evat-pm** [turbonomic/t8c-install#6]
Deploying Turbonomic into an OCP 4.7 cluster running k8s, returns an error on a deprecated API version as of 1.16 (v1beta1)- can we can use v1alpha1?
![image](https://user-images.githubusercontent.com/11505818/115476441-7a952e80-a207-11eb-812d-598ca5d73839.png)

**Comment by esara** [comment]
@evat-pm v1 CRD was published at
https://github.com/turbonomic/t8c-install/blob/master/operator/config/crd/bases/charts.helm.k8s.io_xls.yaml
in preparation of the deprecated api being removed in v1.22, but in the meantime, we have customers running on previous k8s versions, where only the v1vbeta1 crd is supported.
