### ISSUE TITLE
switch_dbs_mount_point.sh does not work in very old OVA v7.17.x

### ISSUE THREAD

**Issue by shawsers** [turbonomic/t8c-install#8]
The script https://github.com/turbonomic/t8c-install/blob/master/bin/switch_dbs_mount_point.sh does not work in very old OVA 7.17.9 and should be updated with that detail to prevent customers from running it.  I ran it at a customer today and it didn't work and had to be manually fixed.  Adding a check for the old filesystem used in 7.17.x: /dev/mapper/vg_turbo_db-lv_turbo_db will resolve it or check for that and don't allow customers to run it if detected or update the script to support it.  Any questions let me know, thanks

**Comment by esara** [comment]
thanks Shawn for the comment, I think we have no more then one or two customers running that old virtual machine build.
instead of supporting it with the script, I would rather migrate them to a newer build for many reasons / security fixes and stability on top of the list.
