### ISSUE TITLE
Problem with local run in WSL environment

### ISSUE THREAD

**Issue by rednevals** [turbonomic/t8c-install#9]
I have generated the t8c-operator image sucessfully. When running 'make run' I encounter the following error:

`$ make run
/home/sxl73/repos/t8c-install/operator/bin/helm-operator run
{"level":"info","ts":1626789384.7728796,"logger":"cmd","msg":"Version","Go Version":"go1.15.5","GOOS":"linux","GOARCH":"amd64","helm-operator":"v1.4.0+git","commit":"98f30d59ade2d911a7a8c76f0169a7de0dec37a0"}
{"level":"info","ts":1626789384.775094,"logger":"cmd","msg":"WATCH_NAMESPACE environment variable not set. Watching all namespaces.","Namespace":""}
{"level":"info","ts":1626789385.330956,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"error","ts":1626789385.331422,"logger":"cmd","msg":"Failed to create new manager factories.","Namespace":"","error":"invalid chart directory /opt/helm/helm-charts/xl: stat /opt/helm/helm-charts/xl: no such file or directory","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/operator-framework/operator-sdk/internal/cmd/helm-operator/run.run\n\tinternal/cmd/helm-operator/run/cmd.go:147\ngithub.com/operator-framework/operator-sdk/internal/cmd/helm-operator/run.NewCmd.func1\n\tinternal/cmd/helm-operator/run/cmd.go:68\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895\nmain.main\n\tcmd/helm-operator/main.go:40\nruntime.main\n\t/opt/hostedtoolcache/go/1.15.5/x64/src/runtime/proc.go:204"}
make: *** [Makefile:38: run] Error 1`

Any ideas?

**Comment by rednevals** [comment]
I also attempted to deploy to my local cluster:

`$ kubectl apply -f https://raw.githubusercontent.com/turbonomic/t8c-install/master/operator/deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic
error: unable to recognize "https://raw.githubusercontent.com/turbonomic/t8c-install/master/operator/deploy/crds/charts_v1alpha1_xl_cr.yaml": no matches for kind "Xl" in version "charts.helm.k8s.io/v1"`

**Comment by esara** [comment]
@rednevals please follow the deployment steps in 
https://github.com/turbonomic/t8c-install/blob/master/DEPLOY.md
in general, you can use the image that is already built and published into dockerhub
but you will need to apply the crd before you can use an operator (for any operator, not just this one)

**Comment by rednevals** [comment]
Thanks, I will give that a try.

In a recent PR that I authored, a change was made to fully support SMTP endpoints that do not require auth parameters. How is this supported using the Helm chart and values.yaml? i.e MEDIAWIKI_ENABLE_SMTP_AUTH=no

https://github.com/bitnami/bitnami-docker-mediawiki/pull/98

**Comment by esara** [comment]
@rednevals I am sorry, but I am not familiar with the bitname mediawiki containerized deployment, maybe you can ask a question in that project? the t8c-operator does not manage smtp endpoints.

**Comment by rednevals** [comment]
I had issues with the the second approach. So, I opened a ticket:

https://support.turbonomic.com/hc/en-us/requests/116504

**Comment by rednevals** [comment]
Turns out I do not have the required RAM available to stand this up on my laptop...
